services:

  postgres:
    image: postgres:15
    container_name: payments_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payments
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  wallet-service:
    build:
      context: .
      dockerfile: services/wallet-service/Dockerfile
    ports:
      - "3001:3001"

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    ports:
      - "3002:3002"

  ledger-service:
    build:
      context: .
      dockerfile: services/ledger-service/Dockerfile

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "3000:3000"